name = "PicoScope"
uuid = "6e55bc00-3941-41e9-8a91-3db1928a100e"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
