name = "PicoScope"
uuid = "6e55bc00-3941-41e9-8a91-3db1928a100e"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
libps5000a_jll = "e5de8f98-00d2-5fcf-8fb0-95a2d4fe7562"

[compat]
Libdl = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
